export const GET_COUNTRIES = 'COUNTRIES/GET_COUNTRIES';
export const COUNTRIES_LOADING_TRUE = 'COUNTRIES/COUNTRIES_LOADING_TRUE';
export const COUNTRIES_LOADING_FALSE = 'COUNTRIES/COUNTRIES_LOADING_FALSE';
