export const GET_COUNTRIES = 'COUNTRIES/GET_COUNTRIES';
export const GET_COUNTRY_BY_ISO = 'COUNTRIES/GET_COUNTRY_BY_ISO';
export const GET_COUNTRY_ON_ERROR = 'COUNTRIES/GET_COUNTRY_ON_ERROR';
export const COUNTRIES_LOADING_TRUE = 'COUNTRIES/COUNTRIES_LOADING_TRUE';
export const COUNTRIES_LOADING_FALSE = 'COUNTRIES/COUNTRIES_LOADING_FALSE';
