export const GET_TOTAL_STATS = 'TOTAL_STATS/GET_TOTAL_STATS';
export const TOTAL_STATS_LOADING_TRUE = 'TOTAL_STATS/TOTAL_STATS_LOADING_TRUE';
export const TOTAL_STATS_LOADING_FALSE =
  'TOTAL_STATS/TOTAL_STATS_LOADING_FALSE';
